using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System;
using System.ServiceModel;
using System.Xml.Serialization;

namespace WindowsFormsApp1.TechExpertRef
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Этот код создан программой.
    //
    //     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
    //     повторного создания кода.
    // </auto-generated>
    //------------------------------------------------------------------------------



        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
        [System.ServiceModel.ServiceContractAttribute(Namespace = "http://kodekssoap.org/", ConfigurationName = "TechExpertRef.apiSoap")]
        public interface apiSoap
        {

            [System.ServiceModel.OperationContractAttribute(Action = "http://kodekssoap.org/GetSearchListN", ReplyAction = "*")]
            [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
            [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchConditionString))]
            [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchConditionNumber))]
            [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchConditionDouble))]
            [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchConditionDate))]
            [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchConditionClassificator))]
            [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchCondition))]
            [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DjvuDocInfo))]
            [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
            [return: System.ServiceModel.MessageParameterAttribute(Name = "ArrayOfDocListItem")]
            TechExpertRef.GetSearchListNResponse GetSearchListN(TechExpertRef.GetSearchListNRequest request);

            [System.ServiceModel.OperationContractAttribute(Action = "http://kodekssoap.org/FuzzySearch", ReplyAction = "*")]
            [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true)]
            [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchConditionString))]
            [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchConditionNumber))]
            [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchConditionDouble))]
            [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchConditionDate))]
            [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchConditionClassificator))]
            [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SearchCondition))]
            [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DjvuDocInfo))]
            [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
            [return: System.ServiceModel.MessageParameterAttribute(Name = "DocListInfo")]
            TechExpertRef.DocListInfo FuzzySearch(string arg0, string arg1, int arg2, string arg3, string arg4);

        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
        [System.ServiceModel.MessageContractAttribute(WrapperName = "GetSearchListN", WrapperNamespace = "http://kodekssoap.org/", IsWrapped = true)]
        public partial class GetSearchListNRequest
        {

            [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "1", Order = 0)]
            public string arg0;

            [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "1", Order = 1)]
            public object arg1;

            [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "1", Order = 2)]
            public int arg2;

            [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "1", Order = 3)]
            public string arg3;

            [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "1", Order = 4)]
            public string arg4;

            [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "1", Order = 5)]
            public bool arg5;

            public GetSearchListNRequest()
            {
            }

            public GetSearchListNRequest(string arg0, object arg1, int arg2, string arg3, string arg4, bool arg5)
            {
                this.arg0 = arg0;
                this.arg1 = arg1;
                this.arg2 = arg2;
                this.arg3 = arg3;
                this.arg4 = arg4;
                this.arg5 = arg5;
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
        [System.ServiceModel.MessageContractAttribute(WrapperName = "GetSearchListNResponse", WrapperNamespace = "http://kodekssoap.org/", IsWrapped = true)]
        public partial class GetSearchListNResponse
        {

            [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
            [System.Xml.Serialization.XmlArrayAttribute()]
            [System.Xml.Serialization.XmlArrayItemAttribute("item_DocListItem", Namespace = "http://kodekssoap.org/", IsNullable = false)]
            public TechExpertRef.DocListItem[] ArrayOfDocListItem;

            public GetSearchListNResponse()
            {
            }

            public GetSearchListNResponse(TechExpertRef.DocListItem[] ArrayOfDocListItem)
            {
                this.ArrayOfDocListItem = ArrayOfDocListItem;
            }
        }


        public class DocsInfoAttrItem
        {
            [System.Xml.Serialization.XmlElement(Order = 0)]
            public string name { get; set; }

            [System.Xml.Serialization.XmlElement(Order = 1)]
            public int attr { get; set; }

            [System.Xml.Serialization.XmlElement(Order = 2)]
            public int type { get; set; }

            [System.Xml.Serialization.XmlElement(Order = 3, IsNullable = true)]
            public object value { get; set; }

            [System.Xml.Serialization.XmlElement(Order = 4)]
            public string description { get; set; }
        }


        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://kodekssoap.org/")]
        public partial class DocListInfo
        {

            private string idField;

            private int sizeField;

            private int partsField;

            private int dppField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
            public string id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
            public int size
            {
                get
                {
                    return this.sizeField;
                }
                set
                {
                    this.sizeField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
            public int parts
            {
                get
                {
                    return this.partsField;
                }
                set
                {
                    this.partsField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
            public int dpp
            {
                get
                {
                    return this.dppField;
                }
                set
                {
                    this.dppField = value;
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://kodekssoap.org/")]
        public partial class DocListItem
        {

            private int ndField;

            private int rField;

            private string typeField;

            private string nameField;

            private string infoField;

            private bool haskdocField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
            public int nd
            {
                get
                {
                    return this.ndField;
                }
                set
                {
                    this.ndField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
            public int r
            {
                get
                {
                    return this.rField;
                }
                set
                {
                    this.rField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
            public string type
            {
                get
                {
                    return this.typeField;
                }
                set
                {
                    this.typeField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
            public string name
            {
                get
                {
                    return this.nameField;
                }
                set
                {
                    this.nameField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
            public string info
            {
                get
                {
                    return this.infoField;
                }
                set
                {
                    this.infoField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
            public bool haskdoc
            {
                get
                {
                    return this.haskdocField;
                }
                set
                {
                    this.haskdocField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://kodekssoap.org/")]
        public partial class ThesObjs
        {

            private int offsetjField;

            private int offsetiField;

            private ThesObj[] objsField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
            public int offsetj
            {
                get
                {
                    return this.offsetjField;
                }
                set
                {
                    this.offsetjField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
            public int offseti
            {
                get
                {
                    return this.offsetiField;
                }
                set
                {
                    this.offsetiField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
            [System.Xml.Serialization.XmlArrayItemAttribute("item_ThesObj", IsNullable = false)]
            public ThesObj[] objs
            {
                get
                {
                    return this.objsField;
                }
                set
                {
                    this.objsField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://kodekssoap.org/")]
        public partial class ThesObj
        {

            private int ndField;

            private string phrasesField;

            private string titleField;

            private string statusField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
            public int nd
            {
                get
                {
                    return this.ndField;
                }
                set
                {
                    this.ndField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
            public string phrases
            {
                get
                {
                    return this.phrasesField;
                }
                set
                {
                    this.phrasesField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
            public string title
            {
                get
                {
                    return this.titleField;
                }
                set
                {
                    this.titleField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
            public string status
            {
                get
                {
                    return this.statusField;
                }
                set
                {
                    this.statusField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://kodekssoap.org/")]
        public partial class SearchConditionString
        {

            private int idField;

            private string valueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
            public int id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
            public string value
            {
                get
                {
                    return this.valueField;
                }
                set
                {
                    this.valueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://kodekssoap.org/")]
        public partial class SearchConditionNumber
        {

            private int idField;

            private string valueField;

            private int modeField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
            public int id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
            public string value
            {
                get
                {
                    return this.valueField;
                }
                set
                {
                    this.valueField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
            public int mode
            {
                get
                {
                    return this.modeField;
                }
                set
                {
                    this.modeField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://kodekssoap.org/")]
        public partial class SearchConditionDouble
        {

            private int idField;

            private float[] valuesField;

            private int modeField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
            public int id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
            public float[] values
            {
                get
                {
                    return this.valuesField;
                }
                set
                {
                    this.valuesField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
            public int mode
            {
                get
                {
                    return this.modeField;
                }
                set
                {
                    this.modeField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://kodekssoap.org/")]
        public partial class SearchConditionDate
        {

            private int idField;

            private string[] valuesField;

            private int modeField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
            public int id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
            [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
            public string[] values
            {
                get
                {
                    return this.valuesField;
                }
                set
                {
                    this.valuesField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
            public int mode
            {
                get
                {
                    return this.modeField;
                }
                set
                {
                    this.modeField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://kodekssoap.org/")]
        public partial class SearchConditionClassificator
        {

            private int idField;

            private int[] valuesField;

            private string lopField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
            public int id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
            public int[] values
            {
                get
                {
                    return this.valuesField;
                }
                set
                {
                    this.valuesField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
            public string lop
            {
                get
                {
                    return this.lopField;
                }
                set
                {
                    this.lopField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://kodekssoap.org/")]
        public partial class SearchCondition
        {

            private int idField;

            private string valueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
            public int id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
            public string value
            {
                get
                {
                    return this.valueField;
                }
                set
                {
                    this.valueField = value;
                }
            }
        }


        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://kodekssoap.org/")]
        public partial class DjvuDocInfo
        {

            private int ndField;

            private int hidxField;

            private object rField;

            private int pageCountField;

            private string urlField;

            private DjvuPageInfo[] pagesField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
            public int nd
            {
                get
                {
                    return this.ndField;
                }
                set
                {
                    this.ndField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
            public int hidx
            {
                get
                {
                    return this.hidxField;
                }
                set
                {
                    this.hidxField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
            public object r
            {
                get
                {
                    return this.rField;
                }
                set
                {
                    this.rField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
            public int pageCount
            {
                get
                {
                    return this.pageCountField;
                }
                set
                {
                    this.pageCountField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
            public string url
            {
                get
                {
                    return this.urlField;
                }
                set
                {
                    this.urlField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayAttribute(Order = 5)]
            [System.Xml.Serialization.XmlArrayItemAttribute("item_DjvuPageInfo", IsNullable = false)]
            public DjvuPageInfo[] pages
            {
                get
                {
                    return this.pagesField;
                }
                set
                {
                    this.pagesField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://kodekssoap.org/")]
        public partial class DjvuPageInfo
        {

            private int widthField;

            private int heightField;

            private int dpiField;

            private int pageNumField;

            private string urlField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
            public int width
            {
                get
                {
                    return this.widthField;
                }
                set
                {
                    this.widthField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
            public int height
            {
                get
                {
                    return this.heightField;
                }
                set
                {
                    this.heightField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
            public int dpi
            {
                get
                {
                    return this.dpiField;
                }
                set
                {
                    this.dpiField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
            public int pageNum
            {
                get
                {
                    return this.pageNumField;
                }
                set
                {
                    this.pageNumField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
            public string url
            {
                get
                {
                    return this.urlField;
                }
                set
                {
                    this.urlField = value;
                }
            }
        }


        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
        public interface apiSoapChannel : TechExpertRef.apiSoap, System.ServiceModel.IClientChannel
        {
        }


        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]

        public partial class apiSoapClient : System.ServiceModel.ClientBase<TechExpertRef.apiSoap>, TechExpertRef.apiSoap
        {

            /// <summary>
            /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
            /// </summary>
            /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
            /// <param name="clientCredentials">Учетные данные клиента.</param>
            static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

            public apiSoapClient() :
                    base(apiSoapClient.GetDefaultBinding(), apiSoapClient.GetDefaultEndpointAddress())
            {
                this.Endpoint.Name = EndpointConfiguration.apiSoap.ToString();
                ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
            }


            [return: MessageParameter(Name = "DocListInfo")]
            public TechExpertRef.DocListInfo FuzzySearch(string arg0, string arg1, int arg2, string arg3, string arg4)
            {
                return base.Channel.FuzzySearch(arg0, arg1, arg2, arg3, arg4);
            }

            public virtual System.Threading.Tasks.Task OpenAsync()
            {
                return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
            }

            public virtual System.Threading.Tasks.Task CloseAsync()
            {
                return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
            }

            private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
            {
                if ((endpointConfiguration == EndpointConfiguration.apiSoap))
                {
                    System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                    result.MaxBufferSize = int.MaxValue;
                    //result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                    result.MaxReceivedMessageSize = int.MaxValue;
                    result.AllowCookies = true;
                    return result;
                }
                throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
            }

            private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
            {
                if ((endpointConfiguration == EndpointConfiguration.apiSoap))
                {
                    return new System.ServiceModel.EndpointAddress("http://192.168.0.14:81/docs/api");
                }
                throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
            }

            private static System.ServiceModel.Channels.Binding GetDefaultBinding()
            {
                return apiSoapClient.GetBindingForEndpoint(EndpointConfiguration.apiSoap);
            }

            private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
            {
                return apiSoapClient.GetEndpointAddress(EndpointConfiguration.apiSoap);
            }

            public TechExpertRef.GetSearchListNResponse GetSearchListN(TechExpertRef.GetSearchListNRequest request)
            {
                return base.Channel.GetSearchListN(request);
            }


            public enum EndpointConfiguration
            {

                apiSoap,
            }
        }
    }

